### ISSUE TITLE
元数据我觉得可以使用结构体定义 这样的话 就可以少很多位运算。

### ISSUE THREAD

**Issue by ffashion** [yangminz/bcst_csapp#12]

**Comment by yangminz** [comment]
很多地方不使用`struct`是为了扩展性，用`struct`定义就确定了实现，但用函数定义，就像接口一样，对未来可能的修改留下空间。不过你具体指的是哪些地方的metadata，不同的地方考虑的东西会不太一样。

**Comment by ffashion** [comment]
malloc 的matedata 。因为 如果我觉得 没有struct的话 会在代码里面写很多 常量。 这可能会使得代码阅读变得有些困难。
