### ISSUE TITLE
Chapter3疑问

### ISSUE THREAD

**Issue by cuikangyuan** [yangminz/bcst_csapp#13]
大佬，请问图中这个sh_size没对应上，是笔误还是哪里我没理解对呢？
![image](https://user-images.githubusercontent.com/13326015/149056996-dc71184f-0441-47c3-b8b1-de4b0b164f5a.png)

**Comment by yangminz** [comment]
谢谢指出，是我笔误了，这里0x10是.data section，而不是.text，.text是0xe
