### ISSUE TITLE
视频《第七章：链接 》部分的代码，运行报错 

### ISSUE THREAD

**Issue by ehello** [yangminz/bcst_csapp#15]
@yangminz 

对于https://github.com/yangminz/bcst_csapp/tree/2abfc251ed681dced6012f54459b291c29b45fd5 处的代码，

我运行./cmd.py l
发现./bin/test_elf 运行抱错：
_**test_elf: ./src/algorithm/hashtable.c:266: insert_bucket_tail: Assertion `b->karray[b->counter] == NULL' failed.
Aborted (core dumped)**_

不知道为什么跟视频里的结果不一样
![image](https://user-images.githubusercontent.com/50838571/154972808-a584465a-6024-4ccd-a792-2c5ee82ddaf4.png)

**Comment by yangminz** [comment]
可以git log看一下你所在的commit吗，可以把commit id贴给我看一下

**Comment by ehello** [comment]
就是 2abfc251ed681dced6012f54459b291c29b45fd5   @yangminz

**Comment by yangminz** [comment]
> 就是 [2abfc25](https://github.com/yangminz/bcst_csapp/commit/2abfc251ed681dced6012f54459b291c29b45fd5) @yangminz

但是这个commit hashtable.c在datastructure下，但我看你的报错在algorithm目录下，是改过什么吗

**Comment by ehello** [comment]
![image](https://user-images.githubusercontent.com/50838571/155124586-d96c5c5b-8045-496c-a455-2cfadf3fbf22.png)

**Comment by ehello** [comment]
比对了一下，可能是hashtable.c的问题，[2abfc251ed681dced6012f54459b291c29b45fd5](https://github.com/yangminz/bcst_csapp/tree/2abfc251ed681dced6012f54459b291c29b45fd5) 的hashtable.c 不是最新的

**Comment by yangminz** [comment]
如果要更进一步的debug：
./cmd.py debug l
进入gdb以后：
> run
> backtrace
可以给我看一下函数stack

**Comment by ehello** [comment]
比对了一下，可能是hashtable.c的问题，

[2abfc251ed681dced6012f54459b291c29b45fd5](https://github.com/yangminz/bcst_csapp/tree/2abfc251ed681dced6012f54459b291c29b45fd5) 下的hashtable.c 不是最新的。

替换成最新提交的hashtable.c就好了

![image](https://user-images.githubusercontent.com/50838571/155127509-30f5c9cd-3106-43ba-859b-4fa5de0ffd6c.png)

**Comment by yangminz** [comment]
构造函数里忘记赋值了23333
