### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by lsy1109** [yangminz/bcst_csapp#16]
请问这个项目是有点类似nemu这种的模拟器吗？另外怎么没看到makefile啊

**Comment by hnlcf** [comment]
项目没有makefile（其实最开始有），编译配置在 [`cmd.py`](https://github.com/yangminz/bcst_csapp/blob/dev/cmd.py) 中， `build` 函数下的 [`gcc_map`](https://github.com/yangminz/bcst_csapp/blob/dev/cmd.py#L167) 保存了不同目标的编译选项，可以通过 `python cmd.py build <target-name>` 执行不同目标的编译

**Comment by yangminz** [comment]
`cmd.py`最近又改了一下，现在是`cmd.py --build <module name>`

**Comment by lsy1109** [comment]
佬，就是说如果我想要学习csapp的话，是看您的这个项目代码和视频还是去看nemu呢？

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年7月1日 11:20
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [yangminz/bcst_csapp] 请教一下 (Issue #16)


cmd.py最近又改了一下，现在是cmd.py --build <module name>

―
