### ISSUE TITLE
commit id 80b1e88 的几个疑问

### ISSUE THREAD

**Issue by aprz512** [yangminz/bcst_csapp#19]
1. jmp_handler ，jmp指令应该不改变条件码吧，csapp 第3版第3章家庭作业ex3.73 遇到过，重置条件码是不是会有问题。
2. sub_handler，x - y 用 x + （~y + 1） 来实现，为啥不直接 x - y 呢？

**Comment by yangminz** [comment]
1. 查了一下指令集手册，确实不应该改flag，当时复制黏贴代码写错了，没有碰到触发Bug的情况
2. 这个单纯是为了表现ALU加法器，所以尽量使用逻辑电路的表达方法。其实应该在这里写一个ALU模拟器的

**Comment by aprz512** [comment]
get
