### ISSUE TITLE
输出的值和预设的值不同

### ISSUE THREAD

**Issue by maojinhua** [yangminz/bcst_csapp#6]
你好~最近看到了你b站的视频，觉得很不错。我在git上面下载了你的代码，然后在本地运行，发现两个问题请教一下，谢谢。

## 运行环境：
- mac

## 修改的地方：
- makFile下的命令我从原来的gcc-7换成了gcc。
 ![image](https://user-images.githubusercontent.com/13777695/134800301-dc6e68f9-8de6-4cb1-807a-3603ca9f18c5.png)

## 问题一：输出的值和代码里预设的值不同~
![image](https://user-images.githubusercontent.com/13777695/134800280-743a3e51-1443-4eac-a58c-9cab3f14f144.png)

## 问题二：
- printf里格式化的地方，我要改成0x%016llx，不然会报错
```ormat specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]```

![image](https://user-images.githubusercontent.com/13777695/134800350-d0081b11-d1aa-4fa5-b806-84d23bfb674d.png)

## 问题三：
- 初始化寄存器的值是根据什么依据来初始化的呢
![image](https://user-images.githubusercontent.com/13777695/134800793-e48c2bc0-951d-4f71-b225-97f3d9a5a7e8.png)

**Comment by yangminz** [comment]
Hello~

Q1: 可能代码比较老了，如果不对的话，可以看一下后续的几个commit，是不是有修正

Q2: printf格式化字符串时，64-bit的hex number，具体看编译器和系统。`%lx`打印`unsigned long int`, `%llx`打印`unsigned long long int`，但`unsigned long int`在某些系统上是32位，某些系统上是64位。不过确实用`%llx`比较没有歧义

Q3: 初始值是通过GBD得到的。需要你自己写一下add.c程序，gdb break到`main()`，然后通过`info r`查看寄存器得到。Stack上的信息也是通过GDB得到的。

**Comment by Leixiaoxiang** [comment]
Q1:  --> 我的环境 ubuntu 20.04 64 bit，使用 gcc-7，将 -O2 变更为 -O0，此时汇编程序和 UP 一致。
       --> 寄存器的初始值需要使用自己环境下 gdb 的 info r 的值，不能实际抄 UP 的，运行结束之后数据一致。

建议 UP 可以使用 vscode gdb 调试，这样不用写对比代码，debug 脚本如下：
![image](https://github.com/yangminz/bcst_csapp/assets/66509052/00c17819-18b6-40ae-b73c-e3739e193cd6)
